### ISSUE TITLE
Are you considering moving this to Caffeine?

### ISSUE THREAD

**Issue by JanecekPetr** [ben-manes/concurrentlinkedhashmap#45]
Or is it completely inappropriate nowadays and would require some major work from you (e.g. a rewrite on top of Java 8's ConcurrentHashMap)?

**Comment by ben-manes** [comment]
Caffeine is effectively that major rewrite, but uses an API similar to the one we designed for Guava. It should be easy to [migrate](https://github.com/ben-manes/caffeine/wiki/ConcurrentLinkedHashMap) over to.

CLHM uses a backport of Java 8's ConcurrentHashMap, but lacks support for atomic compute methods. That was an invasive change to support in Caffeine (replacing CAS loops with synchronized blocks). A lot of work went into optimizations resulting in [higher performance](https://github.com/ben-manes/caffeine/wiki/Benchmarks) across the board.

Is there anything in particular that you were looking for, other than a class with the same name? Is there confusion that a doc fix would help clarify?

**Comment by JanecekPetr** [comment]
Ah. Yes, minor confusion caused my misunderstanding. I didn't find a link to [`Caffeine` JavaDoc](http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/1.2.0/com/github/benmanes/caffeine/cache/Caffeine.html) anywhere. Not on the [home page](https://github.com/ben-manes/caffeine), not on the [wiki home page](https://github.com/ben-manes/caffeine/wiki), not on the [Cache wiki page](https://github.com/ben-manes/caffeine/wiki/Cache). Now I'm clear, thank you.

Anyway, since you asked - the original thing I was looking for was, literally, a `LinkedHashMap` suitable for concurrent use, not a cache per se. I understand the difference and that the new project has a Guava-cache-like API etc.

I'll simply use the good old CLHM for now, and will also experiment with various `Caffeine` weighter configurations. Thanks!

**Comment by ben-manes** [comment]
The JavaDoc badge on the home page seemed like the easiest way to promote the link and keep it updated as new releases come out. The home page probably needs to be rewritten to better explain usage and highlight important links.

Note that CLHM has always been the caching portion of LinkedHashMap (LRU mode), since that's the most common need / hard part of a concurrent version. An insertion-ordered ConcurrentMap is fairly trivial to implement, or write an adequate work around, so that feature was never provided since it contrasts significantly in design details from the LRU portion.

**Comment by ben-manes** [comment]
I rewrote Caffeine's home page so it should be clearer. Thanks for the tip.
