### ISSUE TITLE
build failure...

### ISSUE THREAD

**Issue by abhijitSingh86** [ben-manes/concurrentlinkedhashmap#46]
I am trying to build this project, but build is failing because of org.cachebench:cache-benchmark:jar jar not found. I checked in maven, but it is not there too. 
Let me know how to build this project

**Comment by ben-manes** [comment]
Sorry, moving to github the build notes were moved into [NOTES](https://github.com/ben-manes/concurrentlinkedhashmap/blob/master/NOTES). The `cachebench` jar has to be installed locally as it was a JBoss Cache tool that wasn't put on Central, but used when one of their developer's blogged about it. I think it was rebranded Railgun and I hadn't realized & upgraded.

Also note that you have to build using JDK6/7 due to the `ConcurrentHashMapV8` method collisions with the default methods in Map. Alternately, you can safely remove that class and use `ConcurrentHashMap`.

**Comment by ben-manes** [comment]
Closing as the build instructions provide the command to install the `lib/cache-benchmark` jar locally. Please reopen if you run into any other build problems.
