### ISSUE TITLE
Google App Engine error: sun.misc.Unsafe is a restricted class

### ISSUE THREAD

**Issue by johnpoth** [ben-manes/concurrentlinkedhashmap#47]
Hi Ben,

I'm currently experiencing an issue with ConcurrentHashMapV8 on google app engine:

Caused by: java.lang.NoClassDefFoundError: sun.misc.Unsafe is a restricted class. Please see the Google App Engine developer's guide for more details.
    at com.google.apphosting.runtime.security.shared.stub.sun.misc.Unsafe.<clinit>(Unsafe.java)
    at org.apache.camel.com.googlecode.concurrentlinkedhashmap.ConcurrentHashMapV8.getUnsafe(ConcurrentHashMapV8.java:4136)

Does it make sense to create a patch for this considering the performance impact? I also noticed sun.misc.Unsafe is used in the caffeine project.

Thanks!

**Comment by ben-manes** [comment]
You could either downgrade to 1.3.x or patch to use to drop `ConcurrentHashMapV8`. The newer hash map is faster, but only used through the `ConcurrentMap` interface so it is easy to drop. There's some gains in v1.4 regardless, but I think either approach is okay. Otherwise the library doesn't use Unsafe.

Fedora repackaged the library to drop CHMv8 (see #44). I don't know if that's hosted on a Maven repository to let you quickly source from there instead.

Caffeine uses Unsafe a lot to avoid memory bloat of `Atomic` objects and optimize memory barriers. The plan is to remove the usage in JDK9 ([VarHandles](http://openjdk.java.net/jeps/193)). I don't plan on starting that until JDK9 is ready for release, though.

The other option is to use Guava. I wrote an GAE app a long time ago and the provided JVM had almost no headroom given the tiny memory limit. I think I ended up using soft references (despite being evil) because I couldn't determine a reasonable size and instances were killed regularly regardless.

**Comment by ben-manes** [comment]
I just noticed that this is for Camel which shades the jar. That makes it harder patch and they've recently [started to upgrade](https://issues.apache.org/jira/browse/CAMEL-8602) to Caffeine. So this would require a patch release and an upgraded Camel release. That could be a bit of a headache if you want a quick turnaround.

Do GAE managed VMs put these types of restrictions in place? That might be the best option, since the traditional VMs with Java were known to be a very poor experience.

**Comment by ben-manes** [comment]
@johnpoth It [appears](https://issues.jboss.org/browse/ENTESB-5115) that Camel resolved this by deprecating the GAE support. Is that an acceptable resolution?

**Comment by johnpoth** [comment]
Hi ben, yes that should do it :D Thanks for your help!
