### ISSUE TITLE
Relation between data.size and capacity

### ISSUE THREAD

**Issue by bishwenduk029** [ben-manes/concurrentlinkedhashmap#52]
@ben-manes , I was trying to understand the implementation more from a perspective of learning. I was having some difficulty understanding the relation between the capacity of the concurrent-LHP and the size of backing concurrent-HP. When running scenarios I see the size of the backing map is ver high and not honouring the maximum capacity.

I am not raising this as an issue but more from the perspective of understanding if this could lead to a memory leak?

**Comment by ben-manes** [comment]
When an entry is added to the backing map a corresponding task is added to the `writeQueue`. That queue is drained as soon as possible by acquiring a tryLock, running the queued tasks, and evicting if needed. In this implementation, the write queue is implemented as an unbounded `ConcurrentLinkedQueue`. That can mean runaway growth in a synthetic stress test. This won't happen in a realistic scenario because that requires the application to do nothing itself, as even a small pause to do regular application logic allows the cache to catch up and drain the queues.

Caffeine uses a similar design, but makes many improvements. There the write queue is a lock-free ring buffer with a maximum size (thanks to JCTools' [MpscGrowableArrayQueue](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscGrowableArrayQueue.java)). If this queue is full then [backpressure](https://github.com/ben-manes/caffeine/blob/7bca129d01c9b6a3cb16454e2fa5ee0f4d00dd31/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1422-L1448) is applied by forcing the calling thread to acquire the eviction lock and assist in the maintenance work. This unschedules that thread, making the lock holder to have a greater chance of being given a cpu slice (resolving priority inversion problems). While this too allows the cache to grow beyond the maximum, it ensures a low upper bound to avoid the risk of a memory leak scenario.

**Comment by bishwenduk029** [comment]
Thanks You @ben-manes for your response. I understand now why backing map feels unbounded under synthetic stress test, but in real scenarios the draining of queues will help keep the memory in check.

I do feel Caffeine is awesome. But I am enjoying going step by step starting at Concurrent-LHP helps build concepts which makes understanding Caffeine easier.

Thanks for your contributions, these implementations have so many concurrent design patterns that I am learning from.
